# Generated by Django 6.0 on 2025-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('ma_cthd', models.AutoField(db_column='MaCTHD', primary_key=True, serialize=False)),
                ('so_luong', models.IntegerField(db_column='SoLuong')),
                ('don_gia', models.DecimalField(db_column='DonGia', decimal_places=2, max_digits=18)),
                ('thanh_tien', models.DecimalField(db_column='ThanhTien', decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'CHI_TIET_HOA_DON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hd', models.AutoField(db_column='MaHD', primary_key=True, serialize=False)),
                ('ngay_lap', models.DateTimeField(db_column='NgayLap')),
                ('tong_tien', models.DecimalField(db_column='TongTien', decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'HOA_DON',
                'managed': False,
            },
        ),
    ]
