# Generated by Django 6.0 on 2025-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('ma_chuc_vu', models.AutoField(db_column='MaChucVu', primary_key=True, serialize=False)),
                ('ten_chuc_vu', models.CharField(db_column='TenChucVu', max_length=50)),
                ('phu_cap', models.DecimalField(db_column='PhuCap', decimal_places=2, default=0, max_digits=18)),
                ('he_so_luong', models.DecimalField(db_column='HeSoLuong', decimal_places=2, default=1, max_digits=5)),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CHUC_VU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nv', models.AutoField(db_column='MaNV', primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(db_column='HoTen', max_length=100)),
                ('sdt', models.CharField(blank=True, db_column='SDT', max_length=15, null=True)),
                ('dia_chi', models.CharField(blank=True, db_column='DiaChi', max_length=255, null=True)),
            ],
            options={
                'db_table': 'NHAN_VIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThamSoLuong',
            fields=[
                ('ma_tham_so', models.AutoField(db_column='MaThamSo', primary_key=True, serialize=False)),
                ('ten_tham_so', models.CharField(db_column='TenThamSo', max_length=100)),
                ('gia_tri_so', models.DecimalField(blank=True, db_column='GiaTriSo', decimal_places=2, max_digits=18, null=True)),
                ('gia_tri_chu', models.CharField(blank=True, db_column='GiaTriChu', max_length=255, null=True)),
                ('ngay_hieu_luc', models.DateField(db_column='NgayHieuLuc')),
                ('ghi_chu', models.CharField(blank=True, db_column='GhiChu', max_length=255, null=True)),
            ],
            options={
                'db_table': 'THAM_SO_LUONG',
                'managed': False,
            },
        ),
    ]
